import Sidebar from "@/components/Sidebar";
import UserSideBar from "@/components/UserSideBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};
export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="pt-36">
      <div className="flex">
        <UserSideBar />
        <div className="flex-1">{children}</div>
      </div>
    </section>
  );
}
